added: cli arguments for both the port and host
shubham1172/remote-play pull request #41
Opened 2022-09-30 20:42 UTC by zt4ff

2022-10-01 03:24 UTC, shubham1172 requested changes
Hello @zt4ff, thank you for your PR, requested some changes!

2022-10-01 03:24 UTC, shubham1172 commented on main.py
> +                host = int(sys.argv[i+1])
`host` is not an `int`. See line 129.

2022-10-01 03:24 UTC, shubham1172 commented on main.py
> +                port = int(sys.argv[i+1])
Please handle converting string to int and avoid runtime issues. You can catch it gracefully, log, and exit.

2022-10-01 05:59 UTC, zt4ff commented
@shubham1172, I resolved the comments. Thanks.

2022-10-01 06:05 UTC, shubham1172 commented on main.py
> +                except:
```suggestion
                except ValueError:
```

2022-10-01 06:11 UTC, shubham1172 commented on main.py
> +                    exit("The --port argument should be a number")
```suggestion
                    console.log(f"Error: invalid --port, {verr}, exiting", color="r")
                    sys.exit(1)
```

2022-10-01 06:21 UTC, zt4ff commented
updated

2022-10-01 06:21 UTC, shubham1172 commented on main.py
> +
```suggestion
```

2022-10-01 06:23 UTC, shubham1172 commented on main.py
> +                    console.log(f"Error: invalid --port, {verr}, exiting", color="r")
```suggestion
                    console.log(
                        f"Error: invalid --port, {verr}, exiting", color="r")
```

2022-10-01 06:25 UTC, shubham1172 approved these changes
Thank you @zt4ff for your contributions.

To many more contributions! 🎉

2022-10-01 06:25 UTC, merged

2022-10-07 18:16 UTC, zt4ff commented
closes #40